### ISSUE TITLE
Many characters must be escaped for JS

### ISSUE THREAD

**Issue by jpambrun** [HansKre/markdown-execute#2]
The following doesn't work:

```js
let i = 12;
console.log("ab$cd")
console.log("ab$$cd")
console.log('sdfdsgdfg')
console.log(`ab${i}cd`)
```

as it results in 
```
❯ node -e "let i = 12;
∙ console.log('ab$cd')
∙ console.log('ab$$cd')
∙ console.log('sdfdsgdfg')
∙ console.log(`ab${i}cd`)
∙ "
bash: abcd: command not found
ab
ab2847cd
sdfdsgdfg
```

Many characters needs to be escaped. Alternatively, the markdown block can the piped into node's stdin.

**Comment by HansKre** [comment]
Hello @jpambrun 
Good catch, thx! Will have a look into it. If you like, your contribution would be very welcome as well.

**Comment by HansKre** [comment]
Fixed:

![image](https://github.com/HansKre/markdown-execute/assets/7346919/01d8eaa7-1060-4ea2-8c99-9f59402820b3)
