### ISSUE TITLE
When executing a bash block, it keeps opening a new terminal

### ISSUE THREAD

**Issue by kloudwrangler** [HansKre/markdown-execute#43]
I have a markdown file with bash in a code block. I press `execute command in terminal as Shell-Script` and it keeps opening a new terminal session every time I press that button.

**Comment by HansKre** [comment]
Thank you for reporting the issue. May I ask whish shell e operating system you are using?

**Comment by kloudwrangler** [comment]
Using Zsh (zsh 5.9 (x86_64-apple-darwin23.0)) and MacOS Sonoma (14.0)

**Comment by HansKre** [comment]
Happy Christmas and sorry for getting back to you so late. I was trying to reproduce the issue, but wasn't successful. Although using same version of zsh and macOS, the terminal is getting re-used properly in my case:

<img width="1014" alt="image" src="https://github.com/HansKre/markdown-execute/assets/7346919/dc001e1a-a31e-42bd-b5e2-a3732579c60b">

I understand that this is a very annoying issue. May I get you interested in having a look yourself?

This is the line where terminal-detection starts: https://github.com/HansKre/markdown-execute/blob/a85baa99765764e5c36e075586adc355c82777e4/src/execute.ts#L30

There's a whole block of code dedicated to detecting if the `activeTerminal` returned by VSCode is actually available: https://github.com/HansKre/markdown-execute/blob/a85baa99765764e5c36e075586adc355c82777e4/src/execute.ts#L50

I could imagine, that this is what's not properly working in your case, although I don't know why.

So if I could get you interested in resolving the issue, the way you'd go about debugging is decribed in https://github.com/HansKre/markdown-execute/blob/master/DEVELOPMENT.md

Looking forward to hear from you!

**Comment by HansKre** [comment]
I have optimized the code to re-use first available terminal-window if VSCode-API does not provide an `activeTerminal`. Your feedback if it works would be appreciated.
