### ISSUE TITLE
Python Error: IndentationError: expected an indented block after function definition on line 1

### ISSUE THREAD

**Issue by damiankrolik** [HansKre/markdown-execute#51]
## Problem 
While passing `python` code with indentation in markdown file - indentation is not passed - causing IndentationError:

### example from `md` file
````
```python
def say_hello(name):
  print(f'Hello {name}')
say_hello('World')
```
````

is passed to terminal as:
```
python -c "def say_hello(name):
print(f'Hello {name}')
say_hello('World')
"
```
with no indentation - causing IndentationError.

**Comment by HansKre** [comment]
Should be fixed in version `1.1.0`
