### ISSUE TITLE
Execute in currently active terminal

### ISSUE THREAD

**Issue by edwin-hendriks** [HansKre/markdown-execute#52]
I love this extension, but for me to become useful I need the script to run in the current active terminal. That would be great.

**Comment by HansKre** [comment]
Glad to hear and I totally agree. In fact, that's actually how it is supposed to work.

The extension tries to use the active terminal, only if it's busy it tries to go to the next one opens a new one only as last resort.

Can you please share details of your setup (OS, shell) and other useful details which could help reproduce the issue?

**Comment by edwin-hendriks** [comment]
VS Code running on Windows 11. I use Git bash in most cases as my go-to shell. Below are the details from VS Code:

![image](https://github.com/HansKre/markdown-execute/assets/13136750/c7a3cf25-91b1-43b8-8a0e-3785e70c236f)

**Comment by 0xphilipp** [comment]
I have the same issue on Windows. Always opens a new terminal, for any script.

**Comment by HansKre** [comment]
@edwin-hendriks just to clarify, is it opening the new terminal only first time you execute the command and then reuse the terminal or would it open a new terminal even if you clicked execute second time leaving the terminal open?

@0xphilipp would you please provide an answer on that question as well?

I'm really not sure how to reproduce the issue. I'm thinking to make a release with extensive logging. Another approach to look into could be to not try to get the active terminal but always open a new one, but then keep a reference to it for future executions.

**Comment by HansKre** [comment]
I have published version `1.0.2` with a fix. Please let me know if you are still having issues.

**Comment by edwin-hendriks** [comment]
It now works as I expected. Great. Thanks.

If I now have a terminal open already it will execute the commands from the markdown file in that already open terminal. It does not yet seem to detect if the terminal matches with the commands. E.g.

```bash
ls
```

Will simply run ls in the already open terminal, even if it is powershell or Command prompt.

But to be honest, that is not a necessity.

Thanks for the improvement.


Edwin Hendriks

+31625014678

________________________________
